"""empty message

Revision ID: 02a736abf8b5
Revises: 7e5316ae1a00
Create Date: 2026-05-21 01:06:56.522288

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "02a736abf8b5"
down_revision: Union[str, Sequence[str], None] = "7e5316ae1a00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "stock")
    # ### end Alembic commands ###
