"""empty message

Revision ID: 09bae8f843d4
Revises: 02a736abf8b5
Create Date: 2026-05-22 19:47:32.171809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09bae8f843d4'
down_revision: Union[str, Sequence[str], None] = '02a736abf8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'addresses', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'promocodes', ['promocode_id'], ['id'])
    op.drop_column('orders', 'status_id')
    op.alter_column('product_images', 'path_to_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('products', sa.Column('archived', sa.Boolean(), server_default='false', nullable=False))
    op.create_foreign_key(None, 'roles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'statuses_history', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statuses_history', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('products', 'archived')
    op.alter_column('product_images', 'path_to_image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('orders', sa.Column('status_id', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'user_id')
    # ### end Alembic commands ###
