apiVersion: apps/v1
kind: Deployment

metadata:
  name: sfmshop-deployment

spec:
  replicas: 3

  selector:
    matchLabels:
      app: sfmshop

  template:
    metadata:
      labels:
        app: sfmshop

    spec:
      containers:
        - name: app
          image: sfm_shop:latest

          ports:
            - containerPort: 8000